export const START_HOLIDAYS_REQUEST_FROM_API = "START_HOLIDAYS_REQUEST_FROM_API";
export const END_HOLIDAYS_REQUEST_FROM_API = "END_HOLIDAYS_REQUEST_FROM_API";
export const CHANGE_CITY_OF_HOLIDAYS = "CHANGE_CITY_OF_HOLIDAYS";
export const CHANGE_FAVORITE_HOLIDAY  = "CHANGE_FAVORITE_HOLIDAY";
